---
# Exclude directories and/or files from the conversion. These exclusions are relative to the site's source directory and cannot be outside the source directory.
exclude: ['Gemfile', 'Gemfile.lock']

# Serve the website from this URL
url: https://www.excludedmiddle.net
